### ISSUE TITLE
Refactoring milestones

### ISSUE THREAD

**Issue by drewpts** [drewpts/LPROJ-main#46]
- [x] separate logic for add/removing subproject in ProjectExplorer and API  
- [x] get rid from `list<string>` in API's functions
- [x] tests should be reorganized. Value-parametrized tests should be used again while we simulating unregular conditions.
- [x] Take rid of such info duplication 

``` cpp
throw FileSetRuntimeError(FileSetRuntimeError::AlreadyLoaded, "Project already loaded");
```

**Comment by drewpts** [comment]
* separate logic for add/removing subproject in ProjectExplorer and API

**Comment by mkwork** [comment]
> separate logic for add/removing subproject in ProjectExplorer and API

what did you mean here?

**Comment by drewpts** [comment]
I don't know now what I mean before. :-\ Seems I already get rid from such
stuff in previous commits (about few weeks ago).

2015-05-27 16:43 GMT+03:00 Maxim Kot notifications@github.com:
